name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: 'terraform lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Run terraform fmt check
        run: terraform fmt -check -diff -recursive

  validate:
    name: 'terraform validate'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        run: |
          cd _example
          terraform init -input=false

      - name: Terraform Validate
        id: plan
        continue-on-error: true
        run: |
          cd _example
          terraform validate


  plan:
    name: 'terraform plan'
    needs:
      - lint
      - validate
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: 'Configure AWS Credentials'
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: Initialize Terraform
        run: |
          cd _example
          terraform init -input=false

      - name: Terraform Plan
        id: plan
        continue-on-error: true
        run: |
          cd _example
          terraform plan -input=false -no-color

  pre-commit:
    name: 'Pre-Commit'
    needs:
      - lint
      - plan
      - validate
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Install Tflint'
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
